name: Python package

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Define a cache dependency glob
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      
      - name: Install the project
        run: uv sync --all-extras

      - name: Run Ruff
        run: uv run ruff check --output-format=github .
      
      - name: Run Mypy 
        run: uv run mypy --config-file pyproject.toml service
        
      - name: Run tests
        # For example, using `pytest`
        run: uv run pytest tests
